spring.application.name=scm2.0
server.port=8081


spring.datasource.url=jdbc:mysql://localhost:3306/scm2
spring.datasource.username=root
spring.datasource.password=root


spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update